# This is a config for E2B sandbox template.
# You can use template ID (vrq3kw6qrv4n1sxtpbdr) or template name (my-nextjs-project) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("my-nextjs-project") # Sync sandbox
# sandbox = await AsyncSandbox.create("my-nextjs-project") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('my-nextjs-project')

team_id = "e7915450-88c2-4fa0-b6a3-01b951886246"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "my-nextjs-project"
template_id = "vrq3kw6qrv4n1sxtpbdr"
